[package]
name = "async-backtrace-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-backtrace = "0.2.0"
futures = "0.3.25"
tokio = { version = "1.21.2", features = ["full"] }
