[workspace]
members = [
	"common",
	"constructor-di",
	"cake-pattern-di",
	"shaku-di"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.68.1"

[workspace.dependencies]
anyhow = "1"
actix-web = "4"
