[versions]
kotlin = "2.0.0"
koin = "3.5.6"
koin-ksp = "1.3.1"

[libraries]
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version = "2.3.12" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.1" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotation = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.22" }

[bundles]
ktor = ["ktor-server-netty"]
serialization = ["kotlin-serialization-json"]
koin = ["koin-core", "koin-annotation"]
koin-compiler = ["koin-compiler"]