[package]
name = "async-programming-prac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = "1.12.0"
glommio = "0.7.0"
tokio = { version = "1.20.1", features = ["full"] }
