[package]
name = "benchmark-murmur-xxhash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasthash = "0.4.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "hash"
harness = false
