[workspace]
members = [
	"struct-injection",
	"struct-injection-with-di-container",
	"trait-injection",
	"higher-order-function-injection"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.67.0"

[workspace.dependencies]
actix-web = "4.3.0"
