[package]
name = "static-doubly-linked-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ghost-cell = "0.2.3"
static-rc = "0.6.1"
